import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import QueryProvider from "@/providers/query-client-provider";
import { Toaster } from "react-hot-toast";
import Header from "./components/header";
import "./globals.css";

// Import Inter font
const inter = Nunito_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <QueryProvider>
          <Toaster /> {/* Wrap entire app */}
          <Header />
          <main className="mt-[150px] max-w-7xl mx-auto">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
